language: java
sudo: false # faster builds

script: "mvn clean test -DisLocal=true -DisHeadless=false"

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: target
  on:
    branch: master
cache:
  directories:
  - "$HOME/.cache"