language: java
sudo: false # faster builds

script: "mvn -Dmaven.test.skip=false clean compile package"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: target
  on:
    branch: master
cache:
  directories:
  - "$HOME/.cache"
branches:
  except:
  - legacy
  - experimental

# safelist
branches:
  only:
  - master
  - stable